apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-aggregator
  labels:
    app: webhook-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-aggregator
  template:
    metadata:
      labels:
        app: webhook-aggregator
    spec:
      volumes:
      - name: tmp
        emptyDir: {}
      containers:
      - name: webhook-aggregator
        image: abdennasserbentaleb/webhook-aggregator:0.0.1-SNAPSHOT
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: webhook-aggregator-config
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: webhook-aggregator-config
              key: rabbitmq-port
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-aggregator
spec:
  selector:
    app: webhook-aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-aggregator-config
data:
  rabbitmq-host: "rabbitmq-service"
  rabbitmq-port: "5672"
